### ISSUE TITLE
Improved aes128ctrbs shift row suggestion

### ISSUE THREAD

**Issue by peterdettman** [Ko-/riscvcrypto#1]
Hi, not a user but found my way here via [this paper](https://eprint.iacr.org/2020/1123).

Looking at your shiftrow method for aes128ctrbs we count 6 OR, 7 AND, 6 shifts:

```
.macro shiftrow b0, m0,m1,m2,m3,m4,m5, r0,r1
    andi   \r0, \b0, 0xff
    and    \r1, \b0, \m0
    slli   \r1, \r1, 2
    or     \r0, \r0, \r1
    and    \r1, \b0, \m1
    srli   \r1, \r1, 6
    or     \r0, \r0, \r1
    and    \r1, \b0, \m2
    slli   \r1, \r1, 4
    or     \r0, \r0, \r1
    and    \r1, \b0, \m3
    srli   \r1, \r1, 4
    or     \r0, \r0, \r1
    and    \r1, \b0, \m4
    slli   \r1, \r1, 6
    or     \r0, \r0, \r1
    and    \r1, \b0, \m5
    srli   \r1, \r1, 2
    or     \b0, \r0, \r1
.endm
```

This can be improved quite a bit by changing it to two "masked swaps". Here is Java code from an AESBS implementation (4 blocks bitsliced to 8x64):

```
    private static void shiftRows(long[] s)
    {
        for (int i = 0; i < 8; ++i)
        {
            long u, v;
            u  = s[i];
            v  = (u ^ (u >>> 8)) & 0x00F000FF000F0000L; u ^= (v ^ (v <<  8));
            v  = (u ^ (u >>> 4)) & 0x0F0F00000F0F0000L; u ^= (v ^ (v <<  4));
            s[i] = u;
        }
    }
```

For 32-bit it would be more like (untested):

```
            v  = (u ^ (u >>> 4)) & 0x0C0F0300; u ^= (v ^ (v <<  4));
            v  = (u ^ (u >>> 2)) & 0x33003300; u ^= (v ^ (v <<  2));
```

So, in the first swap we use a distance of 4 and this is enough to swap the two halves of row 2; but we also use it to prepare rows 1 and 3 so that in a second step we can use a distance of 2 and swap cols 1<->2 and 3<->4 for both rows 1 and 3, completing the required shifts.

The cost for this is 6 XOR, 2 AND, 4 shifts, so 12 total vs the original 19.

Sorry I am not familiar enough with riscv to put together a PR.

**Comment by aadomn** [comment]
I confirm this is correct, this would also enhance the performance of the ARM Cortex-M repository at https://github.com/Ko-/aes-armcortexm.

I can work on a PR in the coming days.

We'll also add a comment in [our paper](https://eprint.iacr.org/2020/1123.pdf) to mention it, thanks for highlighting this. However, according to my estimates, the fully-fixsliced implementation should remain faster (probably ~10% gain).

**Comment by peterdettman** [comment]
@aadomn Thank you for the confirmation, and for volunteering to make a PR. If I'm able to implement the fixsliced approach I hope to get you a comparison for my implementation (in Java).

**Comment by peterdettman** [comment]
Closing now that a PR is available: https://github.com/Ko-/riscvcrypto/pull/2 (thanks @aadomn).
